chore(version): test

diff --git a/.forgejo/actions/publish/action.yaml b/.forgejo/actions/publish/action.yaml
--- a/.forgejo/actions/publish/action.yaml
+++ b/.forgejo/actions/publish/action.yaml
@@ -8,11 +8,13 @@ runs:
   steps:
     - name: "Check tag"
       working-directory: ${{ inputs.working-directory }}
+      shell: "nix develop --command bash {0}"
       run: |
-        [[ "v$(nix run flakes nixpkgs#toml-cli --  get Cargo.toml package.version -r)" = "${{ github.ref_name  }}" ]] || (echo "Failed to validate package version. Does not match tag." && false)
+        [[ "v$(toml get Cargo.toml package.version -r)" = "${{ github.ref_name  }}" ]] || (echo "Failed to validate package version. Does not match tag." && false)
 
     - name: "Publish macro"
       working-directory: ${{ inputs.working-directory }}
+      shell: "nix develop --command bash {0}"
       run: |
-        nix run nixpkgs#cargo -- publish
+        cargo -- publish
   
